name: CI Workflow with Docker Login

on:
  push:
    branches: [ master ]

jobs:
  docker-login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to DockerHub using secrets
      run: echo "${{ Moto@1234 }}" | docker login -u "${{ vasanthmano }}" --password-stdin

    - name: Confirm login
      run: docker info
